AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for PowerTools

Resources:
  StudentLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/module/lambda/app.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /students
            Method: POST
            RestApiId: !Ref StudentApi
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/module/lambda/app.ts

  StudentApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowMethods: "'POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Idempotency-Key'"
        AllowOrigin: "'*'"
      DefinitionBody:
        openapi: '3.0.1'
        paths:
          /students:
            post:
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${StudentLambda.Arn}/invocations
                httpMethod: POST
                type: aws_proxy

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${StudentApi}.execute-api.${AWS::Region}.amazonaws.com/dev/students
